Repository M0IM/BE, pull requests merged in 2024-07, with the labels that each got.

#7 👷 Ci: 배포 관련 설정
  .github/workflows/aws.yml
  .gitignore
  Dockerfile
  src/main/resources/application.yml
Labels: 👷‍♂️ ci

#8 :bug: Fix: yml 파일 오류
  .github/workflows/aws.yml
  .gitignore
  src/main/resources/deploy.yml
Labels: 🐛 bug

#9 🐛 Fix: 환경 변수 추가
  .github/workflows/aws.yml
  Dockerfile
Labels: 🐛 bug

#15 📝 Docs: Api 명세서 작성
  src/main/java/com/dev/moim/domain/account/controller/AuthController.java
  src/main/java/com/dev/moim/domain/account/controller/UserController.java
  src/main/java/com/dev/moim/domain/account/dto/AppleAuthRequest.java
  src/main/java/com/dev/moim/domain/account/dto/AuthRequest.java
  src/main/java/com/dev/moim/domain/account/dto/ReissueTokenResponse.java
  src/main/java/com/dev/moim/domain/account/dto/SignInRequest.java
  src/main/java/com/dev/moim/domain/account/dto/SignUpRequest.java
  src/main/java/com/dev/moim/domain/account/dto/SignUpResponse.java
  src/main/java/com/dev/moim/domain/account/dto/TokenResponse.java
  src/main/java/com/dev/moim/domain/moim/CalenderCreateRequest.java
  src/main/java/com/dev/moim/domain/moim/CalenderCreateResponse.java
  src/main/java/com/dev/moim/domain/moim/CalenderDetailGetResponse.java
  src/main/java/com/dev/moim/domain/moim/CalenderGetResponse.java
  src/main/java/com/dev/moim/domain/moim/CalenderSchedule.java
  src/main/java/com/dev/moim/domain/moim/CalenderUpdateResponse.java
  src/main/java/com/dev/moim/domain/moim/ParticipantProfile.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileDetailGetResponse.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileListGetResponse.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileResponse.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileUpdateRequest.java
  src/main/java/com/dev/moim/domain/user/dto/receivedReview.java
  src/main/java/com/dev/moim/global/common/BaseResponse.java
  src/main/java/com/dev/moim/global/error/ExceptionAdvice.java
Labels: 📝 docs

#17 🐛 Fix: swagger 에러
  src/main/java/com/dev/moim/global/config/WebConfig.java
Labels: 🐛 bug

#18 :bug: Fix: aws.yml 교체
  .github/workflows/aws.yml
Labels: 🐛 bug

#19 🐛 Fix: docker image 중복 해결
  .github/workflows/aws.yml
Labels: 🐛 bug

#5 📝 Docs: Api 명세서 작성
  src/main/java/com/dev/moim/domain/account/controller/UserController.java
  src/main/java/com/dev/moim/domain/account/dto/CreateReviewDTO.java
  src/main/java/com/dev/moim/domain/account/dto/ReviewDTO.java
  src/main/java/com/dev/moim/domain/account/dto/ReviewListDTO.java
  src/main/java/com/dev/moim/domain/account/dto/UserPreviewDTO.java
  src/main/java/com/dev/moim/domain/account/dto/UserPreviewListDTO.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
  src/main/java/com/dev/moim/domain/moim/dto/CreateMoimDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/CreateMoimPostDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/CreateMoimPostResultDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/CreateMoimResultDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimAnnouncementPreviewDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimCalendarDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimCommentDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimPostDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimPostPreviewDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimPostPreviewListDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimPreviewDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimPreviewListDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/UpdateMoimDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/WithMoimDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Announcement.java
  src/main/java/com/dev/moim/domain/moim/entity/UserMoim.java
  src/main/java/com/dev/moim/domain/moim/entity/enums/JoinStatus.java
Labels: 📝 docs

#21 ♻️ Refactor: build 문제 해결
  src/main/java/com/dev/moim/domain/account/controller/UserController.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/dto/CreateReviewDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ReviewDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ReviewListDTO.java
  src/main/java/com/dev/moim/domain/user/dto/UserPreviewDTO.java
  src/main/java/com/dev/moim/domain/user/dto/UserPreviewListDTO.java
Labels: 🐛 bug

#26 :sparkles: Feature: docker image 관리
  .github/workflows/aws.yml
Labels: ✨ feature

#20 ✨ Feature: 로그인 기능 구현
  build.gradle
  src/main/java/com/dev/moim/MoimApplication.java
  src/main/java/com/dev/moim/domain/account/controller/AuthController.java
  src/main/java/com/dev/moim/domain/account/dto/JoinRequest.java
  src/main/java/com/dev/moim/domain/account/dto/JoinResponse.java
  src/main/java/com/dev/moim/domain/account/dto/LoginRequest.java
  src/main/java/com/dev/moim/domain/account/dto/ReissueTokenResponse.java
  src/main/java/com/dev/moim/domain/account/dto/SignUpResponse.java
  src/main/java/com/dev/moim/domain/account/dto/TokenResponse.java
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
  src/main/java/com/dev/moim/domain/account/entity/enums/Gender.java
  src/main/java/com/dev/moim/domain/account/entity/enums/Role.java
  src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
  src/main/java/com/dev/moim/domain/account/service/AuthService.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
  src/main/java/com/dev/moim/domain/moim/dto/CalenderCreateRequest.java
  src/main/java/com/dev/moim/domain/moim/dto/CalenderCreateResponse.java
  src/main/java/com/dev/moim/domain/moim/dto/CalenderDetailGetResponse.java
  src/main/java/com/dev/moim/domain/moim/dto/CalenderGetResponse.java
  src/main/java/com/dev/moim/domain/moim/dto/CalenderSchedule.java
  src/main/java/com/dev/moim/domain/moim/dto/CalenderUpdateResponse.java
  src/main/java/com/dev/moim/domain/moim/dto/ParticipantProfile.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/config/CorsConfig.java
  src/main/java/com/dev/moim/global/config/SwaggerConfig.java
  src/main/java/com/dev/moim/global/config/WebConfig.java
  src/main/java/com/dev/moim/global/error/handler/AuthException.java
  src/main/java/com/dev/moim/global/redis/config/RedisConfig.java
  src/main/java/com/dev/moim/global/redis/entity/RefreshToken.java
  src/main/java/com/dev/moim/global/redis/repository/RefreshTokenRepository.java
  src/main/java/com/dev/moim/global/redis/service/RefreshTokenService.java
  src/main/java/com/dev/moim/global/security/annotation/AuthUser.java
  src/main/java/com/dev/moim/global/security/annotation/AuthUserArgumentResolver.java
  src/main/java/com/dev/moim/global/security/annotation/ExtractToken.java
  src/main/java/com/dev/moim/global/security/annotation/ExtractTokenArgumentResolver.java
  src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
  src/main/java/com/dev/moim/global/security/exception/JwtAccessDeniedHandler.java
  src/main/java/com/dev/moim/global/security/exception/JwtAuthenticationEntryPoint.java
  src/main/java/com/dev/moim/global/security/filter/JwtExceptionFilter.java
  src/main/java/com/dev/moim/global/security/filter/JwtFilter.java
  src/main/java/com/dev/moim/global/security/filter/LoginFilter.java
  src/main/java/com/dev/moim/global/security/principal/PrincipalDetails.java
  src/main/java/com/dev/moim/global/security/principal/PrincipalDetailsService.java
  src/main/java/com/dev/moim/global/security/util/HttpResponseUtil.java
  src/main/java/com/dev/moim/global/security/util/JwtUtil.java
Labels: ✨ feature

#29 🐛 Fix: 유저 엔티티 문자열 값 설정 수정
  src/main/java/com/dev/moim/domain/account/controller/AuthController.java
  src/main/java/com/dev/moim/domain/account/dto/JoinRequest.java
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
Labels: 🐛 bug

#31 MM-18 chore: github actions 수정
  .github/workflows/aws.yml
Labels: chore

#34 📝 Docs: 스웨거 명세 수정
  src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
  src/main/java/com/dev/moim/domain/account/entity/enums/ProfileType.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
  src/main/java/com/dev/moim/domain/moim/dto/CalenderCreateResponse.java
  src/main/java/com/dev/moim/domain/moim/dto/CalenderDetailGetResponse.java
  src/main/java/com/dev/moim/domain/moim/dto/CalenderGetResponse.java
  src/main/java/com/dev/moim/domain/moim/dto/CalenderUpdateResponse.java
  src/main/java/com/dev/moim/domain/moim/dto/ParticipantProfile.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanCreateDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanListDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanParticipantListDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanParticipantListPageDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/ScheduleCreateDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/ScheduleGetDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/ScheduleListDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Calendar.java
  src/main/java/com/dev/moim/domain/moim/entity/Schedule.java
  src/main/java/com/dev/moim/domain/moim/entity/enums/Role.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/dto/JoinedMoimDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileCreateDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileDetailDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileDetailGetResponse.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileListDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileListGetResponse.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileResponse.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileUpdateRequest.java
  src/main/java/com/dev/moim/domain/user/dto/ReceivedReviewDTO.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
Labels: 📝 docs

#36 ♻ Refactor: 캘린더 관련 네이밍 변경
  src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
  src/main/java/com/dev/moim/domain/moim/entity/Plan.java
  src/main/java/com/dev/moim/domain/moim/entity/Schedule.java
  src/main/java/com/dev/moim/domain/moim/entity/UserMoim.java
Labels: :recycle: refactor

#37 ✨ Feature: 카카오 로그인 구현
  build.gradle
  src/main/java/com/dev/moim/MoimApplication.java
  src/main/java/com/dev/moim/domain/account/controller/AuthController.java
  src/main/java/com/dev/moim/domain/account/dto/OAuthLoginRequest.java
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
  src/main/java/com/dev/moim/domain/account/service/AuthService.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/error/decoder/FeignErrorDecoder.java
  src/main/java/com/dev/moim/global/security/config/OAuthLoginServiceConfig.java
  src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
  src/main/java/com/dev/moim/global/security/exception/JwtAccessDeniedHandler.java
  src/main/java/com/dev/moim/global/security/exception/JwtAuthenticationEntryPoint.java
  src/main/java/com/dev/moim/global/security/feign/config/KakaoFeignConfiguration.java
  src/main/java/com/dev/moim/global/security/feign/dto/KakaoUserInfo.java
  src/main/java/com/dev/moim/global/security/feign/dto/OAuthUserInfo.java
  src/main/java/com/dev/moim/global/security/feign/request/KakaoFeign.java
  src/main/java/com/dev/moim/global/security/filter/LoginFilter.java
  src/main/java/com/dev/moim/global/security/filter/OAuthLoginFilter.java
  src/main/java/com/dev/moim/global/security/principal/PrincipalDetails.java
  src/main/java/com/dev/moim/global/security/principal/PrincipalDetailsService.java
  src/main/java/com/dev/moim/global/security/service/KakaoLoginService.java
  src/main/java/com/dev/moim/global/security/service/OAuthLoginService.java
  src/main/java/com/dev/moim/global/security/util/JwtUtil.java
Labels: ✨ feature

#40 ✨ Feature: 로그아웃 기능 구현
  src/main/java/com/dev/moim/domain/account/controller/AuthController.java
  src/main/java/com/dev/moim/domain/account/dto/LogoutRequest.java
  src/main/java/com/dev/moim/domain/account/service/AuthService.java
  src/main/java/com/dev/moim/global/redis/config/RedisConfig.java
  src/main/java/com/dev/moim/global/redis/entity/RefreshToken.java
  src/main/java/com/dev/moim/global/redis/repository/RefreshTokenRepository.java
  src/main/java/com/dev/moim/global/redis/service/RefreshTokenService.java
  src/main/java/com/dev/moim/global/redis/util/RedisUtil.java
  src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
  src/main/java/com/dev/moim/global/security/filter/CustomLoginFilter.java
  src/main/java/com/dev/moim/global/security/filter/CustomLogoutHandler.java
  src/main/java/com/dev/moim/global/security/filter/JwtFilter.java
  src/main/java/com/dev/moim/global/security/filter/OAuthLoginFilter.java
  src/main/java/com/dev/moim/global/security/util/JwtUtil.java
Labels: 🐛 bug, ✨ feature

#43 ♻️ Refactor: 시큐리티 로직 리팩토링
  src/main/java/com/dev/moim/domain/account/controller/AuthController.java
  src/main/java/com/dev/moim/domain/account/dto/AppleAuthRequest.java
  src/main/java/com/dev/moim/domain/account/dto/AuthRequest.java
  src/main/java/com/dev/moim/domain/account/dto/JoinRequest.java
  src/main/java/com/dev/moim/domain/account/dto/JoinResponse.java
  src/main/java/com/dev/moim/domain/account/dto/OAuthLoginRequest.java
  src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
  src/main/java/com/dev/moim/domain/account/service/AuthService.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/common/code/status/SuccessStatus.java
  src/main/java/com/dev/moim/global/security/annotation/AuthUserArgumentResolver.java
  src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
  src/main/java/com/dev/moim/global/security/exception/JwtAuthenticationEntryPoint.java
  src/main/java/com/dev/moim/global/security/feign/config/OauthProperties.java
  src/main/java/com/dev/moim/global/security/filter/CustomLoginFilter.java
  src/main/java/com/dev/moim/global/security/filter/JwtExceptionFilter.java
  src/main/java/com/dev/moim/global/security/filter/JwtFilter.java
  src/main/java/com/dev/moim/global/security/filter/OAuthLoginFilter.java
  src/main/java/com/dev/moim/global/security/principal/PrincipalDetails.java
  src/main/java/com/dev/moim/global/security/principal/PrincipalDetailsService.java
  src/main/java/com/dev/moim/global/security/service/OIDCService.java
  src/main/java/com/dev/moim/global/security/util/HttpResponseUtil.java
  src/main/java/com/dev/moim/global/security/util/JwtOIDCUtil.java
  src/main/java/com/dev/moim/global/security/util/JwtUtil.java
  src/main/java/com/dev/moim/global/security/util/OAuthAuthenticationProvider.java
  src/main/java/com/dev/moim/global/security/util/OAuthAuthenticationToken.java
Labels: 🐛 bug, 📝 docs, ✨ feature, :recycle: refactor

#45 ✨ Feature: 이메일 인증 기능 구현
  build.gradle
  src/main/java/com/dev/moim/domain/account/controller/AuthController.java
  src/main/java/com/dev/moim/domain/account/dto/EmailVerificationCodeDTO.java
  src/main/java/com/dev/moim/domain/account/dto/EmailVerificationResultDTO.java
  src/main/java/com/dev/moim/domain/account/service/AuthService.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/email/EmailConfig.java
  src/main/java/com/dev/moim/global/email/EmailUtil.java
  src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
Labels: ✨ feature

#48 👷 Ci: ci/cd 설정
  .ebextensions-dev/00-makeFiles.config
  .ebextensions-dev/01-set-timezone.config
  .github/workflows/aws.yml
  .github/workflows/dev_deploy.yml
  .gitignore
  .platform/nginx.conf
  Dockerfile
  Procfile
  src/main/java/com/dev/moim/global/common/RootController.java
  src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
  src/main/resources/application-database.yml
  src/main/resources/application-jwt.yml
  src/main/resources/application-mail.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application-redis.yml
  src/main/resources/application.yml
Labels: 👷‍♂️ ci

#50 🐛 Fix: build.gradle 수정
  build.gradle
Labels: 🐛 bug

#51 📝 Docs: swagger 명세서 수정
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimAnnouncementDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimAnnouncementListDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimIntroduceDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimPreviewDTO.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/dto/CreateReviewDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ReviewDTO.java
Labels: 📝 docs

#57 🐛 Fix: swagger https url 허용
  src/main/java/com/dev/moim/global/config/SwaggerConfig.java
Labels: 🐛 bug

#58 ♻️ Refactor: 회원가입 DTO 수정
  src/main/java/com/dev/moim/domain/account/controller/AuthController.java
  src/main/java/com/dev/moim/domain/account/dto/EmailDTO.java
  src/main/java/com/dev/moim/domain/account/dto/TokenResponse.java
  src/main/java/com/dev/moim/domain/account/entity/enums/Provider.java
  src/main/java/com/dev/moim/domain/account/service/AuthService.java
  src/main/java/com/dev/moim/global/redis/util/RedisUtil.java
  src/main/java/com/dev/moim/global/security/filter/CustomLoginFilter.java
  src/main/java/com/dev/moim/global/security/filter/OAuthLoginFilter.java
  src/main/resources/application.yml
Labels: :recycle: refactor

#60 ✨ Feat: 유저 프로필 조회 기능 구현
  src/main/java/com/dev/moim/domain/user/UserService.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileDTO.java
  src/main/java/com/dev/moim/global/security/annotation/AuthUserArgumentResolver.java
Labels: ✨ feature
