Repository M0IM/BE, pull requests merged in 2024-08, with the labels that each got.

#62 🐛 Fix: 회원가입 시 유저 계정 중복 검증 로직 수정
  src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
  src/main/java/com/dev/moim/domain/account/service/AuthService.java
Labels: 🐛 bug

#64 ✨ Feat: 회원가입 DTO 검증 로직 구현
  build.gradle
  src/main/java/com/dev/moim/domain/account/controller/AuthController.java
  src/main/java/com/dev/moim/domain/account/dto/JoinRequest.java
  src/main/java/com/dev/moim/domain/account/service/AuthService.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/error/ExceptionAdvice.java
  src/main/java/com/dev/moim/global/validation/annotation/LocalAccountValidation.java
  src/main/java/com/dev/moim/global/validation/annotation/OAuthAccountValidation.java
  src/main/java/com/dev/moim/global/validation/annotation/PasswordValidation.java
  src/main/java/com/dev/moim/global/validation/validator/LocalAccountValidator.java
  src/main/java/com/dev/moim/global/validation/validator/OAuthAccountValidator.java
  src/main/java/com/dev/moim/global/validation/validator/PasswordValidator.java
Labels: 🐛 bug, ✨ feature

#77 ✨ Feature: 캘린더 생성, 조회 기능 구현
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanCreateDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanDayListDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanMonthListDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanParticipantListDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanParticipantListPageDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/ScheduleCreateDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/ScheduleGetDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/ScheduleListDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Plan.java
  src/main/java/com/dev/moim/domain/moim/entity/Schedule.java
  src/main/java/com/dev/moim/domain/moim/entity/UserMoim.java
  src/main/java/com/dev/moim/domain/moim/repository/PlanRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/ScheduleRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/UserPlanRepository.java
  src/main/java/com/dev/moim/domain/moim/service/CalenderCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/CalenderQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/user/UserService.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileDTO.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/error/handler/MoimException.java
  src/main/java/com/dev/moim/global/redis/config/RedisConfig.java
  src/main/java/com/dev/moim/global/security/service/OIDCService.java
  src/main/java/com/dev/moim/global/validation/annotation/MoimValidation.java
  src/main/java/com/dev/moim/global/validation/annotation/PlanValidation.java
  src/main/java/com/dev/moim/global/validation/annotation/UserMoimValidaton.java
  src/main/java/com/dev/moim/global/validation/validator/LocalAccountValidator.java
  src/main/java/com/dev/moim/global/validation/validator/MoimValidator.java
  src/main/java/com/dev/moim/global/validation/validator/OAuthAccountValidator.java
  src/main/java/com/dev/moim/global/validation/validator/PasswordValidator.java
  src/main/java/com/dev/moim/global/validation/validator/PlanValidator.java
  src/main/java/com/dev/moim/global/validation/validator/UserMoimValidator.java
Labels: ✨ feature

#79 ✨ Feature: 유저 개인 일정 조회 기능 구현
  src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/MoimPlanDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanDayListDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanMonthListDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/UserPlanDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/IndividualPlan.java
  src/main/java/com/dev/moim/domain/moim/repository/IndividualPlanRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/UserPlanRepository.java
  src/main/java/com/dev/moim/domain/moim/service/CalenderQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/user/UserService.java
  src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
Labels: ✨ feature

#83 ✨ Feature: presigned url 생성
  build.gradle
  src/main/java/com/dev/moim/global/s3/S3Config.java
  src/main/java/com/dev/moim/global/s3/controller/S3Controller.java
  src/main/java/com/dev/moim/global/s3/dto/AwsDTO.java
  src/main/java/com/dev/moim/global/s3/service/S3Service.java
  src/main/resources/application-s3.yml
  src/main/resources/application.yml
Labels: ✨ feature

#86 ✨ Feature: presigned url list 추가
  src/main/java/com/dev/moim/global/s3/controller/S3Controller.java
  src/main/java/com/dev/moim/global/s3/dto/AwsDTO.java
  src/main/java/com/dev/moim/global/s3/service/S3Service.java
Labels: ✨ feature

#85 ✨ Feature: 유저 프로필 crud 기능 구현
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
  src/main/java/com/dev/moim/domain/account/repository/UserProfileRepository.java
  src/main/java/com/dev/moim/domain/account/repository/UserReviewRepository.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanCreateDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanParticipantListPageDTO.java
  src/main/java/com/dev/moim/domain/user/UserService.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileDetailDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileListDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ReceivedReviewDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ReviewDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ReviewListDTO.java
  src/main/java/com/dev/moim/domain/user/service/UserService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/error/handler/UserException.java
  src/main/java/com/dev/moim/global/validation/annotation/ExistUserValidation.java
  src/main/java/com/dev/moim/global/validation/validator/ExistUserValidator.java
Labels: ✨ feature

#89 ✨ Feature : 모임 crud 기능 구현
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/controller/enums/MoimRequestType.java
  src/main/java/com/dev/moim/domain/moim/dto/CreateMoimDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/CreateMoimResultDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimPreviewDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimPreviewListDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/UpdateMoimDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/WithMoimDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Moim.java
  src/main/java/com/dev/moim/domain/moim/entity/MoimImage.java
  src/main/java/com/dev/moim/domain/moim/entity/enums/MoimCategory.java
  src/main/java/com/dev/moim/domain/moim/repository/ExitReasonRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/MoimImageRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/MoimRepository.java
  src/main/java/com/dev/moim/domain/moim/service/MoimCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostQueryServiceImpl.java
Labels: ✨ feature

#97 ✨ Feature: 유저 프로필 수정 기능 구현
  src/main/java/com/dev/moim/domain/account/dto/LogoutRequest.java
  src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
  src/main/java/com/dev/moim/domain/account/service/AuthService.java
  src/main/java/com/dev/moim/domain/moim/entity/UserMoim.java
  src/main/java/com/dev/moim/domain/moim/entity/enums/ProfileStatus.java
  src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileCreateDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileDetailDTO.java
  src/main/java/com/dev/moim/domain/user/dto/UpdateUserInfoDTO.java
  src/main/java/com/dev/moim/domain/user/service/UserCommandService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
Labels: ✨ feature, 🚚 change

#101 🐛 Fix: 유저 후기 조회 수정
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/dto/ReviewListDTO.java
  src/main/java/com/dev/moim/domain/user/service/UserService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserServiceImpl.java
Labels: 🐛 bug

#100 ✨ Feature : 리스트용 presigned url 설정
  src/main/java/com/dev/moim/global/s3/controller/S3Controller.java
  src/main/java/com/dev/moim/global/s3/dto/AwsDTO.java
  src/main/java/com/dev/moim/global/s3/service/S3Service.java
Labels: ✨ feature

#99 ✨ [Feat] 모임 관리 관련 api
  src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/dto/ChangeAuthorityRequestDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/ChangeAuthorityResponseDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimIntroduceDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/UpdateMoimDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Moim.java
  src/main/java/com/dev/moim/domain/moim/entity/UserMoim.java
  src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
  src/main/java/com/dev/moim/domain/moim/service/MoimCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/dto/IntroduceVideoDTO.java
  src/main/java/com/dev/moim/domain/moim/service/impl/dto/UserProfileDTO.java
  src/main/java/com/dev/moim/domain/user/dto/UserPreviewDTO.java
  src/main/java/com/dev/moim/domain/user/dto/UserPreviewListDTO.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/validation/annotation/CheckAdminValidation.java
  src/main/java/com/dev/moim/global/validation/validator/CheckAdminValidator.java
Labels: ✨ feature

#103 ✨ Feature: 유저 정보 조회 기능 추가
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
  src/main/java/com/dev/moim/domain/account/entity/UserReview.java
  src/main/java/com/dev/moim/domain/account/repository/UserReviewRepository.java
  src/main/java/com/dev/moim/domain/moim/dto/post/CommentCommentResponseDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/CommentResponseDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/MoimPostDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/MoimPostPreviewDTO.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/dto/CreateReviewDTO.java
  src/main/java/com/dev/moim/domain/user/dto/CreateReviewResultDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileDetailDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ReviewDTO.java
  src/main/java/com/dev/moim/domain/user/dto/UpdateUserInfoDTO.java
  src/main/java/com/dev/moim/domain/user/service/UserCommandService.java
  src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Labels: ✨ feature, 🚚 change

#105 🐛 Fix: 이미지 네이밍 에러 해결
  src/main/java/com/dev/moim/domain/moim/dto/MoimIntroduceDTO.java
  src/main/java/com/dev/moim/domain/user/dto/UserPreviewDTO.java
Labels: 🐛 bug

#106 ♻️ Refactor: 모임 일정 참여자 조회 쿼리 성능 개선
  src/main/java/com/dev/moim/domain/moim/repository/UserPlanRepository.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
Labels: :recycle: refactor

#107 ✨ Feature: 알림 설정 관련 api
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/dto/AlarmDTO.java
  src/main/java/com/dev/moim/domain/user/service/UserCommandService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
Labels: ✨ feature

#110 ♻️ Refactor : 모임 관련 api 수정
  src/main/java/com/dev/moim/domain/moim/dto/CreateMoimDTO.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
Labels: :recycle: refactor

#112 ✨ Feature : 신규 모임 조회
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/repository/MoimRepository.java
  src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
Labels: ✨ feature

#111 ♻️ Refactor : 좋아요 url 수정
  src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
Labels: :recycle: refactor

#114 ♻️ Refactor: 이미지 처리 방식 변경
  src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
  src/main/java/com/dev/moim/global/s3/controller/S3Controller.java
  src/main/java/com/dev/moim/global/s3/service/S3Service.java
Labels: :recycle: refactor

#116 ✨ Feature: 모임 id 리스트 검증 커스텀 어노테이션 구현
  src/main/java/com/dev/moim/domain/user/dto/UpdateUserInfoDTO.java
  src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
  src/main/java/com/dev/moim/global/validation/annotation/UserMoimListValidation.java
  src/main/java/com/dev/moim/global/validation/validator/UserMoimListValidator.java
Labels: ✨ feature

#120 ✨ Feature: 이미지 업로드 presignedUrl DTO 수정
  src/main/java/com/dev/moim/global/s3/dto/AwsDTO.java
  src/main/java/com/dev/moim/global/s3/service/S3Service.java
Labels: ✨ feature

#118 ✨ Feature: 유저 엔티티 변경
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/account/service/AuthService.java
Labels: ✨ feature

#123 ♻️ Refactor: S3 서비스 로직 수정
  src/main/java/com/dev/moim/global/s3/dto/AwsDTO.java
  src/main/java/com/dev/moim/global/s3/service/S3Service.java
Labels: :recycle: refactor

#125 ♻️ Refactor: S3 서비스 로직 수정
  src/main/java/com/dev/moim/global/s3/dto/AwsDTO.java
  src/main/java/com/dev/moim/global/s3/service/S3Service.java
Labels: :recycle: refactor

#128 🐛 Fix : presigned url 수정
  src/main/java/com/dev/moim/global/s3/service/S3Service.java
Labels: 🐛 bug

#129 ✨ Feature : 게시글 관련 api
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
  src/main/java/com/dev/moim/domain/moim/dto/post/PostBlockDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/PostReportDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/UpdateMoimPostDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Post.java
  src/main/java/com/dev/moim/domain/moim/entity/PostBlock.java
  src/main/java/com/dev/moim/domain/moim/entity/PostReport.java
  src/main/java/com/dev/moim/domain/moim/repository/PostBlockRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/PostReportRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/PostRepository.java
  src/main/java/com/dev/moim/domain/moim/service/PostCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostQueryServiceImpl.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
Labels: ✨ feature

#135 ♻️ Refactor : 모임 조회 관련 수정
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/controller/enums/MoimRequestType.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
Labels: :recycle: refactor

#131 ✨ Feature: 일정 관련 기능 추가
  src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/UserDailyPlanPageDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/IndividualPlan.java
  src/main/java/com/dev/moim/domain/moim/repository/IndividualPlanRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/PlanRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/UserPlanRepository.java
  src/main/java/com/dev/moim/domain/moim/service/CalenderCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/CalenderQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/dto/CreateIndividualPlanRequestDTO.java
  src/main/java/com/dev/moim/domain/user/service/UserCommandService.java
  src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/error/handler/IndividualPlanException.java
  src/main/java/com/dev/moim/global/error/handler/PlanException.java
  src/main/java/com/dev/moim/global/validation/annotation/IndividualPlanValidation.java
  src/main/java/com/dev/moim/global/validation/annotation/UserPlanDuplicateValidation.java
  src/main/java/com/dev/moim/global/validation/annotation/UserPlanValidation.java
  src/main/java/com/dev/moim/global/validation/validator/IndividualPlanValidator.java
  src/main/java/com/dev/moim/global/validation/validator/UserPlanDuplicateValidator.java
  src/main/java/com/dev/moim/global/validation/validator/UserPlanValidator.java
Labels: ✨ feature

#136 🐛 Fix: resolve merge conflict
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Labels: 🐛 bug

#140 ✨ Feature: 일정 수정 기능 구현
  src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/MoimPlanDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanCreateDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Plan.java
  src/main/java/com/dev/moim/domain/moim/entity/Schedule.java
  src/main/java/com/dev/moim/domain/moim/service/CalenderCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/CalenderQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Labels: ✨ feature, 🚚 change

#141 ✨ Feature : 댓글 관련 api
  src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
  src/main/java/com/dev/moim/domain/moim/dto/post/CommentBlockDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/CommentReportDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/CommentResponseDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/CommentUpdateRequestDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Comment.java
  src/main/java/com/dev/moim/domain/moim/entity/CommentBlock.java
  src/main/java/com/dev/moim/domain/moim/entity/CommentReport.java
  src/main/java/com/dev/moim/domain/moim/repository/CommentBlockRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/CommentReportRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/CommentRepository.java
  src/main/java/com/dev/moim/domain/moim/service/PostCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostQueryServiceImpl.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
Labels: ✨ feature

#143 ✨ Feature : 모임 스페이스 조회 api
  src/main/java/com/dev/moim/domain/account/dto/JoinRequest.java
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
  src/main/java/com/dev/moim/domain/account/service/AuthService.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/repository/PlanRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/PostRepository.java
  src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileDetailDTO.java
Labels: ✨ feature

#146 ♻️ Refactor : 채팅방 모임id 수정
  src/main/java/com/dev/moim/domain/chatting/controller/ChatRoomController.java
  src/main/java/com/dev/moim/domain/chatting/repository/CustomChatRoomRepository.java
  src/main/java/com/dev/moim/domain/chatting/repository/CustomChatRoomRepositoryImpl.java
  src/main/java/com/dev/moim/domain/chatting/service/ChatRoomQueryService.java
  src/main/java/com/dev/moim/domain/chatting/service/impl/ChatRoomQueryServiceImpl.java
Labels: :recycle: refactor

#148 ♻️ Refactor : 사진 api 변환
  src/main/java/com/dev/moim/domain/chatting/controller/ChatRoomController.java
  src/main/java/com/dev/moim/domain/chatting/converter/ChatConverter.java
  src/main/java/com/dev/moim/domain/chatting/converter/ChatRoomConverter.java
  src/main/java/com/dev/moim/domain/chatting/dto/ChatRoomDTO.java
  src/main/java/com/dev/moim/domain/chatting/entity/Chat.java
  src/main/java/com/dev/moim/domain/chatting/entity/ChatRoom.java
  src/main/java/com/dev/moim/domain/chatting/service/impl/ChatQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
  src/main/java/com/dev/moim/global/socket/dto/ChattingDTO.java
  src/main/java/com/dev/moim/global/socket/service/SocketService.java
  src/main/java/com/dev/moim/global/validation/annotation/CheckChatRoomValidation.java
Labels: :recycle: refactor

#154 ♻️ Refactor: 날짜, 시간 타입 변경
  src/main/java/com/dev/moim/domain/account/dto/JoinRequest.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanCreateDTO.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderCommandServiceImpl.java
Labels: :recycle: refactor

#155 ✨ Feature: 유저 관련 기능 추가
  src/main/java/com/dev/moim/domain/account/controller/AuthController.java
  src/main/java/com/dev/moim/domain/account/dto/JoinRequest.java
  src/main/java/com/dev/moim/domain/account/dto/UpdatePasswordDTO.java
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
  src/main/java/com/dev/moim/domain/account/service/AuthService.java
  src/main/java/com/dev/moim/domain/moim/entity/UserMoim.java
  src/main/java/com/dev/moim/domain/moim/entity/enums/JoinStatus.java
  src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
  src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
  src/main/java/com/dev/moim/global/validation/annotation/ExistEmailValidation.java
  src/main/java/com/dev/moim/global/validation/annotation/JoinPasswordValidation.java
  src/main/java/com/dev/moim/global/validation/annotation/QuitValidation.java
  src/main/java/com/dev/moim/global/validation/annotation/UpdatePasswordValidation.java
  src/main/java/com/dev/moim/global/validation/validator/ExistEmailValidator.java
  src/main/java/com/dev/moim/global/validation/validator/JoinPasswordValidator.java
  src/main/java/com/dev/moim/global/validation/validator/QuitValidator.java
  src/main/java/com/dev/moim/global/validation/validator/UpdatePasswordValidator.java
Labels: ✨ feature

#156 ♻️ Refactor: 모임 관련 api 수정
  src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
  src/main/java/com/dev/moim/domain/moim/dto/CreateMoimDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimPreviewDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/UpdateMoimDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Moim.java
  src/main/java/com/dev/moim/domain/moim/entity/MoimImage.java
  src/main/java/com/dev/moim/domain/moim/repository/MoimImageRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
Labels: :recycle: refactor

#157 ✨ Feature: 모임 일정 관련 기능 추가
  src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Plan.java
  src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/UserPlanRepository.java
  src/main/java/com/dev/moim/domain/moim/service/CalenderCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/CalenderQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/validation/annotation/PlanAuthorityValidation.java
  src/main/java/com/dev/moim/global/validation/validator/PlanAuthorityValidator.java
Labels: ✨ feature, :recycle: refactor

#159 ✨ Feature: 유저 특정 날짜 일정 개수 조회 기능 구현
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
  src/main/java/com/dev/moim/domain/account/entity/UserReview.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/IndividualPlan.java
  src/main/java/com/dev/moim/domain/moim/entity/Plan.java
  src/main/java/com/dev/moim/domain/moim/entity/UserPlan.java
  src/main/java/com/dev/moim/domain/moim/repository/IndividualPlanRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/PlanRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/UserPlanRepository.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/dto/UserDailyPlanCntDTO.java
  src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
Labels: ✨ feature

#161 ✨ Feature: 행정구역 조회 API 구현
  src/main/java/com/dev/moim/domain/region/controller/RegionController.java
  src/main/java/com/dev/moim/domain/region/dto/RegionDTO.java
  src/main/java/com/dev/moim/domain/region/dto/RegionListDTO.java
  src/main/java/com/dev/moim/domain/region/entity/Dong.java
  src/main/java/com/dev/moim/domain/region/entity/Sido.java
  src/main/java/com/dev/moim/domain/region/entity/Sigungu.java
  src/main/java/com/dev/moim/domain/region/repository/DongRepository.java
  src/main/java/com/dev/moim/domain/region/repository/SidoRepository.java
  src/main/java/com/dev/moim/domain/region/repository/SigunguRepository.java
  src/main/java/com/dev/moim/domain/region/service/RegionQueryService.java
  src/main/java/com/dev/moim/domain/region/service/impl/RegionQueryServiceImpl.java
  src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
Labels: ✨ feature

#162 ✨ Feature: 모임관련 기능 api
  src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/dto/ChangeMoimLeaderRequestDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimJoinConfirmRequestDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimJoinRequestDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimJoinRequestListDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/CommentResponseDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/UserMoim.java
  src/main/java/com/dev/moim/domain/moim/repository/MoimRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
  src/main/java/com/dev/moim/domain/moim/service/MoimCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/dto/JoinRequestDTO.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/validation/validator/CheckAdminValidator.java
Labels: ✨ feature

#163 ✨ Feature : 알림 삭제 기능
  src/main/java/com/dev/moim/domain/account/repository/AlarmRepository.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/service/UserCommandService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
Labels: ✨ feature

#166 ♻️ Refactor : 웹소켓 타임아웃 늘리기
  .platform/nginx.conf
Labels: :recycle: refactor

#168 ♻️ Refactor: 웹소켓 로그 출력
  src/main/java/com/dev/moim/global/socket/handler/TextHandler.java
Labels: :recycle: refactor

#170 ♻️ Refactor: 타임 아웃 늘리기
  .platform/nginx.conf
Labels: :recycle: refactor

#172 ♻️ Refactor: 모임 수정
  src/main/java/com/dev/moim/domain/account/repository/UserProfileRepository.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/UpdateMoimDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Moim.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
Labels: :recycle: refactor

#175 🐛 Fix: 모임 일정 수정 권한 검증 어노테이션 수정
  src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
  src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
  src/main/java/com/dev/moim/global/validation/validator/UserMoimValidator.java
  src/main/java/com/dev/moim/global/validation/validator/UserPlanValidator.java
Labels: 🐛 bug

#176 ✨ Feature: 로그인, 회원가입, 로그아웃 로직에 fcm 토큰 로직 추가
  src/main/java/com/dev/moim/domain/account/dto/JoinRequest.java
  src/main/java/com/dev/moim/domain/account/dto/LoginRequest.java
  src/main/java/com/dev/moim/domain/account/dto/OAuthLoginRequest.java
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/account/service/AlarmCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/account/service/AuthService.java
  src/main/java/com/dev/moim/domain/user/controller/AlarmController.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/service/UserCommandService.java
  src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/firebase/service/FcmService.java
  src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
  src/main/java/com/dev/moim/global/security/event/CustomAuthenticationSuccessEvent.java
  src/main/java/com/dev/moim/global/security/filter/CustomLoginFilter.java
  src/main/java/com/dev/moim/global/security/filter/CustomLogoutHandler.java
  src/main/java/com/dev/moim/global/security/filter/OAuthLoginFilter.java
Labels: ✨ feature

#178 🐛 Fix: 공지사항 문자열 수정
  src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
Labels: 🐛 bug

#182 ♻️ Refactor: 유저 특정 날짜 일정 조회 수정
  src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/UserDailyPlanPageDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/UserPlanDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/IndividualPlan.java
  src/main/java/com/dev/moim/domain/moim/entity/enums/PlanType.java
  src/main/java/com/dev/moim/domain/moim/repository/PlanRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/UserPlanRepository.java
  src/main/java/com/dev/moim/domain/moim/service/CalenderQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/dto/CreateIndividualPlanRequestDTO.java
  src/main/java/com/dev/moim/domain/user/dto/UserDailyPlanPageDTO.java
  src/main/java/com/dev/moim/domain/user/dto/UserPlanDTO.java
  src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
  src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
  src/main/java/com/dev/moim/global/security/exception/JwtAccessDeniedHandler.java
  src/main/java/com/dev/moim/global/security/exception/JwtAuthenticationEntryPoint.java
  src/main/java/com/dev/moim/global/security/filter/CustomLoginFilter.java
  src/main/java/com/dev/moim/global/security/filter/JwtExceptionFilter.java
  src/main/java/com/dev/moim/global/security/filter/OAuthLoginFilter.java
  src/main/java/com/dev/moim/global/util/HttpRequestUtil.java
  src/main/java/com/dev/moim/global/util/HttpResponseUtil.java
  src/main/java/com/dev/moim/global/util/TimeUtil.java
  src/main/resources/application.yml
Labels: ✨ feature, :recycle: refactor, 🚚 change

#181 ♻️ Refactor : 공지 사항 리턴 문자열 수정
  src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
Labels: :recycle: refactor

#184 ✨ Feature : 모임 소개 기능 & 알림 목록 가져오기
  src/main/java/com/dev/moim/domain/account/repository/AlarmRepository.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
  src/main/java/com/dev/moim/domain/moim/controller/enums/PostRequestType.java
  src/main/java/com/dev/moim/domain/moim/entity/enums/PostType.java
  src/main/java/com/dev/moim/domain/moim/repository/PostRepository.java
  src/main/java/com/dev/moim/domain/moim/service/PostQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/dto/AlarmResponseDTO.java
  src/main/java/com/dev/moim/domain/user/dto/AlarmResponseListDTO.java
  src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Labels: ✨ feature

#190 ♻️ Refactor: 웹소켓 시간 늘리기
  .ebextensions-dev/02-nginx-timeout.config
  .platform/nginx.conf
Labels: :recycle: refactor

#188 ♻️ Refactor: 알림 목록 조회 시 생성 시간 추가
  src/main/java/com/dev/moim/domain/user/dto/AlarmResponseDTO.java
Labels: :recycle: refactor

#194 ✨ Feature: fcmToken 검증 로직 추가
  src/main/java/com/dev/moim/domain/account/dto/JoinRequest.java
  src/main/java/com/dev/moim/global/firebase/service/FCMQueryService.java
  src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
  src/main/java/com/dev/moim/global/security/filter/CustomLoginFilter.java
  src/main/java/com/dev/moim/global/security/filter/OAuthLoginFilter.java
  src/main/java/com/dev/moim/global/validation/annotation/FcmTokenValidation.java
  src/main/java/com/dev/moim/global/validation/validator/FcmTokenValidator.java
Labels: ✨ feature

#199 🐛 Fix: fcmToken 빈문자열 처리
  src/main/java/com/dev/moim/global/security/filter/CustomLoginFilter.java
  src/main/java/com/dev/moim/global/security/filter/OAuthLoginFilter.java
  src/main/java/com/dev/moim/global/validation/validator/FcmTokenValidator.java
Labels: 🐛 bug

#201 🐛 Fix: 파일 대소문자 네이밍 변경 에러 해결
  src/main/java/com/dev/moim/global/firebase/service/FcmQueryService.java
Labels: 🐛 bug

#203 ✨ Feature: 유저 프로필 정보 조회 DTO에 provider 추가
  src/main/java/com/dev/moim/domain/user/dto/ProfileDTO.java
Labels: ✨ feature

#197 ♻️ Refactor: 게시글 관련 api 수정
  src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
  src/main/java/com/dev/moim/domain/moim/controller/enums/PostRequestType.java
  src/main/java/com/dev/moim/domain/moim/dto/post/CommentCommentResponseDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/CommentResponseDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/JoinMoimPostsResponseDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/MoimPostDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Comment.java
  src/main/java/com/dev/moim/domain/moim/entity/ReadPost.java
  src/main/java/com/dev/moim/domain/moim/entity/enums/CommentStatus.java
  src/main/java/com/dev/moim/domain/moim/repository/MoimRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/PostRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/ReadPostRepository.java
  src/main/java/com/dev/moim/domain/moim/service/PostQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
Labels: :recycle: refactor

#206 ✨ Feature: 행정구역 검색 기능 구현
  src/main/java/com/dev/moim/domain/region/controller/RegionController.java
  src/main/java/com/dev/moim/domain/region/dto/RegionSearchDTO.java
  src/main/java/com/dev/moim/domain/region/dto/RegionSearchListDTO.java
  src/main/java/com/dev/moim/domain/region/repository/DongRepository.java
  src/main/java/com/dev/moim/domain/region/service/RegionQueryService.java
  src/main/java/com/dev/moim/domain/region/service/impl/RegionQueryServiceImpl.java
Labels: ✨ feature

#212 ✨ Feature: 모임 소개 게시물 조회 DTO 모임 이미지 추가
  src/main/java/com/dev/moim/domain/moim/dto/post/MoimPostPreviewDTO.java
Labels: ✨ feature

#214 ✨ Feature: 모임 소개 게시물 조회 DTO 모임 커버 이미지로 변경
  src/main/java/com/dev/moim/domain/moim/dto/post/MoimPostPreviewDTO.java
Labels: ✨ feature

#215 ♻️ Refactor: 모임 관련 api 수정
  src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimJoinRequestDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/AnnouncementConfirmRequestDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/AnnouncementRequestDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/BlockCommentResponse.java
  src/main/java/com/dev/moim/domain/moim/dto/post/JoinMoimPostsResponseDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Post.java
  src/main/java/com/dev/moim/domain/moim/entity/ReadPost.java
  src/main/java/com/dev/moim/domain/moim/repository/CommentRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/PostRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/ReadPostRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
  src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/PostCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/PostQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Labels: :recycle: refactor

#216 MM-181 fix: 여러개 조회 수정
  src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
Labels: 🐛 bug

#220 ✨ Feature: 특정 연, 월 유저의 일정 모든 타입 함께 조회
  src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
  src/main/java/com/dev/moim/domain/moim/service/CalenderQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Labels: ✨ feature

#223 🐛 Fix: 모임 관련 버그 해결
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
  src/main/java/com/dev/moim/domain/moim/converter/PostConverter.java
  src/main/java/com/dev/moim/domain/moim/dto/post/CommentCommentResponseDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/CommentResponseDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/MoimPostDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/MoimPostPreviewDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/UserMoim.java
  src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostQueryServiceImpl.java
Labels: :recycle: refactor

#224 ✨ Feature 유저 일정 상세 조회 기능 구현
  src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
  src/main/java/com/dev/moim/domain/moim/service/CalenderQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Labels: ✨ feature

#226 ♻️ Refactor: 커스텀 어노테이션 정리
  src/main/java/com/dev/moim/domain/moim/repository/MoimRepository.java
  src/main/java/com/dev/moim/domain/moim/service/CalenderQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
  src/main/java/com/dev/moim/global/validation/annotation/MoimValidation.java
  src/main/java/com/dev/moim/global/validation/annotation/PlanValidation.java
  src/main/java/com/dev/moim/global/validation/validator/ExistUserValidator.java
  src/main/java/com/dev/moim/global/validation/validator/LocalAccountValidator.java
  src/main/java/com/dev/moim/global/validation/validator/MoimValidator.java
  src/main/java/com/dev/moim/global/validation/validator/OAuthAccountValidator.java
  src/main/java/com/dev/moim/global/validation/validator/PlanAuthorityValidator.java
  src/main/java/com/dev/moim/global/validation/validator/PlanValidator.java
  src/main/java/com/dev/moim/global/validation/validator/SelfReviewValidator.java
  src/main/java/com/dev/moim/global/validation/validator/UserMoimValidator.java
  src/main/java/com/dev/moim/global/validation/validator/UserPlanDuplicateValidator.java
  src/main/java/com/dev/moim/global/validation/validator/UserPlanValidator.java
Labels: :recycle: refactor

#227 ✨ Feature: 다른 유저의 참여 모임 조회 기능 구현
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/repository/MoimRepository.java
  src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
Labels: ✨ feature

#232 🐛 Fix: 특정 날짜 유저의 모든 예정된 일정 조회 쿼리 수정
  src/main/java/com/dev/moim/domain/moim/repository/PlanRepository.java
Labels: 🐛 bug

#234 ✨ Feature: plan 엔티티 schedule 업데이트 로직 수정
  src/main/java/com/dev/moim/domain/moim/entity/Plan.java
Labels: ✨ feature

#230 ♻️ Refactor: 초기 값 true로 변경
  src/main/java/com/dev/moim/domain/account/entity/User.java
Labels: :recycle: refactor

#237 ♻️ Refactor: 알림 관련 수정 API
  src/main/java/com/dev/moim/domain/account/entity/Alarm.java
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/account/entity/enums/AlarmDetailType.java
  src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
  src/main/java/com/dev/moim/domain/account/service/AlarmCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/account/service/AlarmService.java
  src/main/java/com/dev/moim/domain/account/service/AuthService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/user/controller/AlarmController.java
  src/main/java/com/dev/moim/domain/user/dto/AlarmCountResponseDTO.java
  src/main/java/com/dev/moim/domain/user/dto/AlarmResponseDTO.java
  src/main/java/com/dev/moim/domain/user/service/UserCommandService.java
  src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
  src/main/java/com/dev/moim/global/firebase/service/FcmService.java
  src/main/java/com/dev/moim/global/socket/service/SocketService.java
Labels: :recycle: refactor

#238 ♻️ Refactor: 모임 관련 수정 api
  src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
  src/main/java/com/dev/moim/domain/moim/dto/post/MoimPostPreviewDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Moim.java
  src/main/java/com/dev/moim/domain/moim/entity/Post.java
  src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Labels: :recycle: refactor

#240 ✨ [Feat] 유저 프로필 상세 조회 DTO 가입된 모임 수 추가
  src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileDetailDTO.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Labels: ✨ feature

#243 🐛 Fix: 모임 게시물 수정
  src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
  src/main/java/com/dev/moim/domain/moim/dto/post/UpdatePostResponseDTO.java
  src/main/java/com/dev/moim/domain/moim/service/PostCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
Labels: 🐛 bug

#245 🐛 Fix: 중복 제거
  src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Labels: 🐛 bug

#247 ♻️ Refactor: 모임 수정 api 수정
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
Labels: :recycle: refactor

#249 ♻️ Refactor: 모임 스페이스 조회 유저 null 허용
  src/main/java/com/dev/moim/domain/account/repository/UserProfileRepository.java
Labels: :recycle: refactor

#251 🐛 Fix: 가입 모임 리스트 조회 쿼리 조건 추가
  src/main/java/com/dev/moim/domain/moim/repository/MoimRepository.java
Labels: 🐛 bug

#254 ✨ Feature: Todo 기능 구현
  src/main/java/com/dev/moim/domain/account/controller/AuthController.java
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimTodoController.java
  src/main/java/com/dev/moim/domain/moim/dto/task/CreateTodoDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/task/TodoAssigneeDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/task/TodoDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/task/TodoDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/task/TodoPageDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/task/UpdateTodoStatusDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/task/UpdateTodoStatusResponseDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Todo.java
  src/main/java/com/dev/moim/domain/moim/entity/TodoImage.java
  src/main/java/com/dev/moim/domain/moim/entity/UserTodo.java
  src/main/java/com/dev/moim/domain/moim/entity/enums/PlanType.java
  src/main/java/com/dev/moim/domain/moim/entity/enums/TodoStatus.java
  src/main/java/com/dev/moim/domain/moim/repository/PlanRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/TodoImageRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/TodoRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/UserTodoRepository.java
  src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/TodoCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/TodoQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/TodoCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/TodoQueryServiceImpl.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/error/handler/TodoException.java
  src/main/java/com/dev/moim/global/validation/annotation/TodoAssigneeValidation.java
  src/main/java/com/dev/moim/global/validation/annotation/TodoStatusValidation.java
  src/main/java/com/dev/moim/global/validation/annotation/TodoTargetUserValidation.java
  src/main/java/com/dev/moim/global/validation/annotation/TodoValidation.java
  src/main/java/com/dev/moim/global/validation/validator/TodoAssigneeValidator.java
  src/main/java/com/dev/moim/global/validation/validator/TodoStatusValidator.java
  src/main/java/com/dev/moim/global/validation/validator/TodoTargetUserValidator.java
  src/main/java/com/dev/moim/global/validation/validator/TodoValidator.java
Labels: ✨ feature

#256 MM-214 refactor: 알림 id 수정
  src/main/java/com/dev/moim/domain/account/entity/Alarm.java
  src/main/java/com/dev/moim/domain/account/service/AlarmCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/account/service/AlarmService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/user/dto/AlarmResponseDTO.java
  src/main/java/com/dev/moim/global/firebase/service/FcmService.java
  src/main/java/com/dev/moim/global/socket/service/SocketService.java
Labels: :recycle: refactor

#258 ✨ Feature: 푸시 알림 추가 (moim & moimPost)
  src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/service/MoimCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
Labels: ✨ feature

#261 🐛 Fix: 알림 수정
  src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Labels: 🐛 bug

#266 ✨ Feature: deviceId가 null인 유저의 accessToken blackList에 추가
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/security/annotation/AuthUserArgumentResolver.java
Labels: ✨ feature

#268 🐛 Fix: owner 권한 부여
  src/main/java/com/dev/moim/domain/moim/dto/ChangeMoimLeaderRequestDTO.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/validation/annotation/CheckOwnerValidation.java
  src/main/java/com/dev/moim/global/validation/validator/CheckOwnerValidator.java
Labels: 🐛 bug

#275 ♻️ Refactor: 모임 탈퇴 수정
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
Labels: :recycle: refactor

#270 🐛 Fix: todo assignee 전체 선택 시 조건 추가
  src/main/java/com/dev/moim/global/validation/validator/TodoTargetUserValidator.java
Labels: 🐛 bug
