Repository M0IM/BE, pull requests merged in 2024-09, with the labels that each got.

#279 🐛 Fix: 알림 처리 방식 변경
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/TodoCommandServiceImpl.java
Labels: 🐛 bug

#280 ✨ Feature: 커서 시작 번호 변경
  src/main/java/com/dev/moim/domain/moim/controller/MoimTodoController.java
  src/main/java/com/dev/moim/domain/moim/service/impl/TodoQueryServiceImpl.java
Labels: ✨ feature

#282 ✨ Featre: 특정 날짜에 예정된 유저의 총 일정 개수에 todo 개수 포함
  src/main/java/com/dev/moim/domain/moim/repository/UserTodoRepository.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Labels: ✨ feature

#288 ✨ Feature: todo 생성 DTO 마감 날짜 타입 변경
  src/main/java/com/dev/moim/domain/moim/dto/task/CreateTodoDTO.java
  src/main/java/com/dev/moim/domain/moim/service/impl/TodoCommandServiceImpl.java
Labels: ✨ feature

#290 ✨ Feature: 모임 todo 진행 상태 enum 추가
  src/main/java/com/dev/moim/domain/moim/controller/MoimTodoController.java
  src/main/java/com/dev/moim/domain/moim/dto/task/TodoAssigneeDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/task/TodoDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/task/TodoDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/task/UpdateTodoStatusDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/task/UpdateTodoStatusResponseDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Todo.java
  src/main/java/com/dev/moim/domain/moim/entity/UserTodo.java
  src/main/java/com/dev/moim/domain/moim/entity/enums/TodoAssigneeStatus.java
  src/main/java/com/dev/moim/domain/moim/entity/enums/TodoStatus.java
  src/main/java/com/dev/moim/domain/moim/repository/UserTodoRepository.java
  src/main/java/com/dev/moim/domain/moim/service/TodoQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/TodoCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/TodoQueryServiceImpl.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/validation/annotation/TodoAssigneeStatusValidation.java
  src/main/java/com/dev/moim/global/validation/validator/TodoAssigneeStatusValidator.java
  src/main/java/com/dev/moim/global/validation/validator/TodoStatusValidator.java
Labels: ✨ feature

#294 ✨ Feature: 모임 todo 관련 로직 수정
  src/main/java/com/dev/moim/domain/moim/controller/MoimTodoController.java
  src/main/java/com/dev/moim/domain/moim/dto/task/AddTodoAssigneeDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/task/DeleteTodoAssigneeDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/task/TodoAssigneeDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/task/TodoDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/task/UpdateTodoDTO.java
  src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
  src/main/java/com/dev/moim/domain/moim/service/TodoCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/TodoQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/TodoCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/TodoQueryServiceImpl.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/validation/annotation/AddAssigneeValidation.java
  src/main/java/com/dev/moim/global/validation/annotation/DeleteAssigneeValidation.java
  src/main/java/com/dev/moim/global/validation/validator/AddAssigneeValidator.java
  src/main/java/com/dev/moim/global/validation/validator/DeleteAssigneeValidator.java
  src/main/java/com/dev/moim/global/validation/validator/TodoAssigneeStatusValidator.java
Labels: 🐛 bug, ✨ feature

#296 ✨ Feature: 모임 todo API 수정
  src/main/java/com/dev/moim/domain/moim/controller/MoimTodoController.java
  src/main/java/com/dev/moim/domain/moim/dto/task/UpdateTodoDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/todo/AddTodoAssigneeDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/todo/CreateTodoDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/todo/DeleteTodoAssigneeDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/todo/TodoAssigneeDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/todo/TodoDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/todo/TodoDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/todo/TodoPageDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/todo/UpdateTodoDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/todo/UpdateTodoStatusDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/todo/UpdateTodoStatusResponseDTO.java
  src/main/java/com/dev/moim/domain/moim/service/TodoCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/TodoQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/TodoCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/TodoQueryServiceImpl.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/validation/annotation/TodoUpdateDueDateValidation.java
  src/main/java/com/dev/moim/global/validation/validator/AddAssigneeValidator.java
  src/main/java/com/dev/moim/global/validation/validator/DeleteAssigneeValidator.java
  src/main/java/com/dev/moim/global/validation/validator/TodoAssigneeStatusValidator.java
  src/main/java/com/dev/moim/global/validation/validator/TodoTargetUserValidator.java
  src/main/java/com/dev/moim/global/validation/validator/TodoUpdateDueDateValidator.java
Labels: 🐛 bug, ✨ feature, 🚚 change

#299 🐛 Fix: 블랙리스트 등록 토큰 처리 버그 해결
  src/main/java/com/dev/moim/global/security/filter/JwtFilter.java
Labels: 🐛 bug

#300 ✨ Feature: exceptionAdvice 에러 처리 정리
  src/main/java/com/dev/moim/domain/moim/controller/MoimTodoController.java
  src/main/java/com/dev/moim/domain/moim/dto/todo/UpdateTodoStatusDTO.java
  src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/error/ExceptionAdvice.java
  src/main/java/com/dev/moim/global/validation/validator/CheckAdminValidator.java
  src/main/java/com/dev/moim/global/validation/validator/CheckCursorValidator.java
  src/main/java/com/dev/moim/global/validation/validator/CheckPageValidator.java
  src/main/java/com/dev/moim/global/validation/validator/CheckSizeValidator.java
  src/main/java/com/dev/moim/global/validation/validator/CheckTakeValidator.java
  src/main/java/com/dev/moim/global/validation/validator/ExistEmailValidator.java
  src/main/java/com/dev/moim/global/validation/validator/ExistUserValidator.java
  src/main/java/com/dev/moim/global/validation/validator/FcmTokenValidator.java
  src/main/java/com/dev/moim/global/validation/validator/IndividualPlanValidator.java
  src/main/java/com/dev/moim/global/validation/validator/JoinPasswordValidator.java
  src/main/java/com/dev/moim/global/validation/validator/LocalAccountValidator.java
  src/main/java/com/dev/moim/global/validation/validator/MoimValidator.java
  src/main/java/com/dev/moim/global/validation/validator/OAuthAccountValidator.java
  src/main/java/com/dev/moim/global/validation/validator/PlanAuthorityValidator.java
  src/main/java/com/dev/moim/global/validation/validator/PlanValidator.java
  src/main/java/com/dev/moim/global/validation/validator/QuitValidator.java
  src/main/java/com/dev/moim/global/validation/validator/SelfReviewValidator.java
  src/main/java/com/dev/moim/global/validation/validator/TodoAssigneeValidator.java
  src/main/java/com/dev/moim/global/validation/validator/TodoUpdateDueDateValidator.java
  src/main/java/com/dev/moim/global/validation/validator/TodoValidator.java
  src/main/java/com/dev/moim/global/validation/validator/UpdatePasswordValidator.java
  src/main/java/com/dev/moim/global/validation/validator/UserMoimListValidator.java
  src/main/java/com/dev/moim/global/validation/validator/UserMoimValidator.java
  src/main/java/com/dev/moim/global/validation/validator/UserPlanDuplicateValidator.java
  src/main/java/com/dev/moim/global/validation/validator/UserPlanValidator.java
Labels: ✨ feature

#302 ✨ Feature: 유저 plan 관련 수정
  src/main/java/com/dev/moim/domain/moim/repository/PlanRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/UserTodoRepository.java
  src/main/java/com/dev/moim/domain/user/dto/UserDailyPlanPageDTO.java
  src/main/java/com/dev/moim/domain/user/dto/UserPlanDTO.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Labels: ✨ feature

#308 ✨ Feature: todo, 일정 관련 스케줄러 기능 구현
  src/main/java/com/dev/moim/MoimApplication.java
  src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/TodoRepository.java
  src/main/java/com/dev/moim/domain/moim/repository/UserTodoRepository.java
  src/main/java/com/dev/moim/domain/moim/service/TodoCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/TodoCommandServiceImpl.java
  src/main/java/com/dev/moim/global/scheduler/PlanScheduler.java
  src/main/java/com/dev/moim/global/scheduler/TodoScheduler.java
Labels: ✨ feature

#310 ✨ Feature: 유저 의견 및 문의사항 보내기 기능 구현
  src/main/java/com/dev/moim/domain/account/controller/AuthController.java
  src/main/java/com/dev/moim/domain/account/dto/InquiryDTO.java
  src/main/java/com/dev/moim/domain/account/service/AuthService.java
  src/main/java/com/dev/moim/global/email/EmailUtil.java
  src/main/java/com/dev/moim/global/error/handler/EmailException.java
Labels: ✨ feature

#306 ♻️ Refactor: 모임 게시판 목록 API
  src/main/java/com/dev/moim/domain/moim/dto/post/AnnouncementRequestDTO.java
  src/main/java/com/dev/moim/domain/moim/repository/PostRepository.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
Labels: :recycle: refactor

#304 ♻️ Refactor: 모임 관련 api 수정
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/controller/enums/MoimRequestType.java
  src/main/java/com/dev/moim/domain/moim/entity/enums/MoimCategory.java
  src/main/java/com/dev/moim/domain/moim/repository/MoimRepository.java
  src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
Labels: :recycle: refactor

#312 ♻️ Refactor: 내가 활동 중인 모임 role 추가
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/controller/enums/MoimRequestRole.java
  src/main/java/com/dev/moim/domain/moim/repository/MoimRepository.java
  src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
Labels: :recycle: refactor

#315 ✨ Feature: 앱 실행 중에도 푸시 알림 뜨도록 priority 설정
  src/main/java/com/dev/moim/domain/moim/service/impl/TodoCommandServiceImpl.java
  src/main/java/com/dev/moim/global/firebase/service/FcmService.java
Labels: ✨ feature

#317 ✨ Feature: 푸시 알림 priority 설정 변경
  src/main/java/com/dev/moim/global/firebase/service/FcmService.java
Labels: ✨ feature

#314 ♻️ Refactor: 인원 제어 수정
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
Labels: :recycle: refactor

#321 🐛 Fix: ApnsConfig에서 aps 설정 추가
  src/main/java/com/dev/moim/global/firebase/service/FcmService.java
Labels: 🐛 bug

#323 🐛 Fix: 푸시 알림 Aps contentAvailable 설정
  src/main/java/com/dev/moim/global/firebase/service/FcmService.java
Labels: 🐛 bug

#326 ✨ Feature: 푸시 알림 iOS 배지 count 제거
  src/main/resources/images/moimLogo.png
Labels: ✨ feature

#327 ✨ Feature: 푸시 알림 iOS 배지 count 제거
  src/main/java/com/dev/moim/global/firebase/service/FcmService.java
Labels: ✨ feature

#329 ♻️ Refactor: FCM 모바일 운영체제 변경
  src/main/java/com/dev/moim/domain/account/entity/enums/AlarmDetailType.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/user/service/impl/ReviewCommandServiceImpl.java
  src/main/java/com/dev/moim/global/firebase/service/FcmService.java
  src/main/java/com/dev/moim/global/socket/service/SocketService.java
Labels: :recycle: refactor

#330 ✨ Feature: 의견 및 문의사항 메일 템플릿 변경
  src/main/java/com/dev/moim/global/email/EmailUtil.java
  src/main/resources/application-image.yml
  src/main/resources/application.yml
  src/main/resources/images/moimLogo.png
Labels: ✨ feature

#332 ✨ Feature: 스케줄러 푸시 알림 모바일 환경 설정 추가
  src/main/java/com/dev/moim/global/firebase/service/FcmService.java
  src/main/java/com/dev/moim/global/scheduler/PlanScheduler.java
  src/main/java/com/dev/moim/global/scheduler/TodoScheduler.java
Labels: ✨ feature

#336 Chore: user 테이블 같이 삭제 추가
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimExpelRequestDTO.java
  src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
  src/main/java/com/dev/moim/domain/moim/service/MoimCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
  src/main/java/com/dev/moim/global/scheduler/UserMoimScheduler.java
Labels: chore

#338 🐛 Fix: 탈퇴한 유저가 작성한 todo 조회 시 에러 해결
  src/main/java/com/dev/moim/domain/moim/dto/todo/TodoDTO.java
  src/main/java/com/dev/moim/domain/moim/service/impl/TodoQueryServiceImpl.java
Labels: 🐛 bug

#340 Chore: 운영 서버 db 반영
  src/main/resources/application.yml
Labels: chore

#342 ✨ Feature: 참여 신청한 모임 일정 조회 DTO에 유저의 moimRole 필드 추가
  src/main/java/com/dev/moim/domain/user/dto/UserDailyPlanPageDTO.java
  src/main/java/com/dev/moim/domain/user/dto/UserPlanDTO.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Labels: ✨ feature

#344 🐛 Fix: 필드 에러 개수에 따른 처리 로직 조건 수정
  src/main/java/com/dev/moim/global/error/ExceptionAdvice.java
Labels: 🐛 bug

#346 🐛 Fix: todo 이미지를 null로 수정했을 때 처리 수정
  src/main/java/com/dev/moim/domain/moim/entity/Todo.java
  src/main/java/com/dev/moim/domain/moim/service/impl/TodoCommandServiceImpl.java
Labels: 🐛 bug

#348 ✨ Feature: 모임장 제외 모임 멤버 조회 기능 구현
  src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
  src/main/java/com/dev/moim/global/validation/validator/CheckOwnerValidator.java
Labels: ✨ feature

#351 ♻️ Refactor: delete mapping body 수정
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimExpelRequestDTO.java
  src/main/java/com/dev/moim/domain/moim/service/MoimCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
Labels: :recycle: refactor

#353 🐛 Fix: 프로필 이미지 url null인 경우 처리
  src/main/java/com/dev/moim/domain/user/dto/ProfileDTO.java
  src/main/java/com/dev/moim/domain/user/dto/ProfileDetailDTO.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Labels: 🐛 bug

#354 ✨ Feature: 멀티 프로필 생성 기능 구현
  src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
  src/main/java/com/dev/moim/domain/moim/entity/UserMoim.java
  src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/dto/CreateProfileDTO.java
  src/main/java/com/dev/moim/domain/user/service/UserCommandService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
Labels: 🐛 bug, ✨ feature

#358 🐛 Fix: 모임 일정 상세 스케줄 startTime 타입 변경
  src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/ScheduleCreateDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/ScheduleGetDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Schedule.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
Labels: 🐛 bug

#360 ✨ Feature: 모임 일정 상세 스케줄 제목 컬럼명 title로 변경
  src/main/java/com/dev/moim/domain/moim/dto/calender/PlanDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/ScheduleGetDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/calender/ScheduleListDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Schedule.java
  src/main/java/com/dev/moim/domain/moim/service/impl/CalenderCommandServiceImpl.java
Labels: ✨ feature

#362 ♻️ Refactor: 댓글 로직 변경
  src/main/java/com/dev/moim/domain/moim/dto/post/CommentCommentResponseDTO.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
Labels: :recycle: refactor

#364 🐛 Fix: 댓글 수정 추가
  src/main/java/com/dev/moim/domain/account/repository/CustomUserRepositoryImpl.java
  src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
  src/main/java/com/dev/moim/domain/chatting/controller/ChatController.java
  src/main/java/com/dev/moim/domain/chatting/controller/ChatRoomController.java
  src/main/java/com/dev/moim/domain/chatting/converter/ChatConverter.java
  src/main/java/com/dev/moim/domain/chatting/converter/ChatRoomConverter.java
  src/main/java/com/dev/moim/domain/chatting/converter/UserChatRoomConverter.java
  src/main/java/com/dev/moim/domain/chatting/dto/ChatDTO.java
  src/main/java/com/dev/moim/domain/chatting/dto/ChatRoomDTO.java
  src/main/java/com/dev/moim/domain/chatting/entity/Chat.java
  src/main/java/com/dev/moim/domain/chatting/entity/ChatRoom.java
  src/main/java/com/dev/moim/domain/chatting/entity/UserChatRoom.java
  src/main/java/com/dev/moim/domain/chatting/repository/ChatRepository.java
  src/main/java/com/dev/moim/domain/chatting/repository/ChatRoomRepository.java
  src/main/java/com/dev/moim/domain/chatting/repository/CustomChatRepository.java
  src/main/java/com/dev/moim/domain/chatting/repository/CustomChatRepositoryImpl.java
  src/main/java/com/dev/moim/domain/chatting/repository/CustomChatRoomRepository.java
  src/main/java/com/dev/moim/domain/chatting/repository/CustomChatRoomRepositoryImpl.java
  src/main/java/com/dev/moim/domain/chatting/repository/UserChatRoomRepository.java
  src/main/java/com/dev/moim/domain/chatting/service/ChatCommandService.java
  src/main/java/com/dev/moim/domain/chatting/service/ChatQueryService.java
  src/main/java/com/dev/moim/domain/chatting/service/ChatRoomCommandService.java
  src/main/java/com/dev/moim/domain/chatting/service/ChatRoomQueryService.java
  src/main/java/com/dev/moim/domain/chatting/service/UserChatRoomCommandService.java
  src/main/java/com/dev/moim/domain/chatting/service/impl/ChatCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/chatting/service/impl/ChatQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/chatting/service/impl/ChatRoomCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/chatting/service/impl/ChatRoomQueryServiceImpl.java
  src/main/java/com/dev/moim/domain/chatting/service/impl/UserChatRoomCommandCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
  src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
  src/main/java/com/dev/moim/global/socket/WebSocketConfig.java
  src/main/java/com/dev/moim/global/socket/dto/ChattingDTO.java
  src/main/java/com/dev/moim/global/socket/handler/CustomWebSocketExceptionHandler.java
  src/main/java/com/dev/moim/global/socket/handler/JWTInterceptor.java
  src/main/java/com/dev/moim/global/socket/handler/SocketUtil.java
  src/main/java/com/dev/moim/global/socket/handler/TextHandler.java
  src/main/java/com/dev/moim/global/socket/service/SocketService.java
  src/main/java/com/dev/moim/global/validation/annotation/CheckChatRoomValidation.java
  src/main/java/com/dev/moim/global/validation/validator/CheckChatRoomValidator.java
  src/main/resources/application-database.yml
Labels: 🐛 bug

#366 ♻️ Refactor: 자신의 role 반환 수정
  src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
  src/main/java/com/dev/moim/domain/moim/dto/MoimRoleResponse.java
  src/main/java/com/dev/moim/domain/moim/service/MoimCommandService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
Labels: :recycle: refactor

#371 🐛 Fix: 프로필 수정 버그 해결
  src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
Labels: 🐛 bug

#373 ✨ Feature: 특정 모임에서 사용할 프로필 수정 API 구현
  src/main/java/com/dev/moim/domain/user/controller/UserController.java
  src/main/java/com/dev/moim/domain/user/dto/UpdateMoimProfileDTO.java
  src/main/java/com/dev/moim/domain/user/service/UserCommandService.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
Labels: ✨ feature

#375 ✨ Feature: 유저 엔티티 성별, 거주지, 생년월일 필드 null 허용
  src/main/java/com/dev/moim/domain/account/dto/JoinRequest.java
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/account/entity/enums/Gender.java
  src/main/java/com/dev/moim/domain/user/dto/UpdateUserDefaultInfoDTO.java
  src/main/java/com/dev/moim/domain/user/dto/UpdateUserInfoDTO.java
Labels: ✨ feature

#377 ✨Feature: 멀티 프로필 적용 전 ver 유저 프로필 수정 DTO 필드 추가
  src/main/java/com/dev/moim/domain/account/entity/User.java
  src/main/java/com/dev/moim/domain/user/dto/UpdateUserInfoDTO.java
  src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
Labels: ✨ feature

#379 ♻️ Refactor: 모임 상세 조회 성별 조회 규칙 변환
  src/main/java/com/dev/moim/domain/moim/dto/MoimDetailDTO.java
  src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
Labels: :recycle: refactor

#381 ✨ Feature: 유저 프로필 상세 조회 DTO 필드 추가
  src/main/java/com/dev/moim/domain/user/dto/ProfileDetailDTO.java
Labels: ✨ feature

#387 ♻️ Refactor: 길이 제한 post
  src/main/java/com/dev/moim/domain/moim/dto/post/AnnouncementRequestDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/CreateMoimPostDTO.java
  src/main/java/com/dev/moim/domain/moim/dto/post/UpdateMoimPostDTO.java
  src/main/java/com/dev/moim/domain/moim/entity/Post.java
Labels: :recycle: refactor

#385 ✨ Feature: 특정 모임에서 할당받은 todo 리스트 조회 기능 구현
  src/main/java/com/dev/moim/domain/moim/controller/MoimTodoController.java
  src/main/java/com/dev/moim/domain/moim/dto/todo/TodoDTO.java
  src/main/java/com/dev/moim/domain/moim/repository/UserTodoRepository.java
  src/main/java/com/dev/moim/domain/moim/service/TodoQueryService.java
  src/main/java/com/dev/moim/domain/moim/service/impl/TodoQueryServiceImpl.java
Labels: ✨ feature

#389 ✨ Feature: redis 연결 에러 처리
  src/main/java/com/dev/moim/domain/account/service/AuthService.java
  src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/moim/global/security/filter/CustomLoginFilter.java
  src/main/java/com/dev/moim/global/security/filter/CustomLogoutHandler.java
  src/main/java/com/dev/moim/global/security/filter/JwtFilter.java
  src/main/java/com/dev/moim/global/security/filter/OAuthLoginFilter.java
  src/main/java/com/dev/moim/global/security/service/OIDCService.java
Labels: ✨ feature

#391 Chore: 서버 분리
  .ebextensions-dev/02-nginx-timeout.config
  .ebextensions-release/00-makeFiles.config
  .ebextensions-release/01-set-timezone.config
  .github/workflows/release_deploy.yml
  .platform/nginx.conf
  src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
  src/main/resources/application-database.yml
  src/main/resources/application-redis.yml
Labels: :recycle: refactor

#395 ♻️ Refactor: swagger 서버 열기
  .ebextensions-release/00-setup-swap.config
  .ebextensions-release/01-makeFiles.config
  .ebextensions-release/02-set-timezone.config
  src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
Labels: :recycle: refactor
